"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Matter = { id: string; title: string; type: string; role: string; status: string; createdAt: string };
type Entry = { id: string; matterId: string; type: string; party: string; outcome: string; source: string; happenedAt: string; notes: string; createdAt: string };
type Evidence = { id: string; matterId: string; name: string; mime: string; size: number; hash: string; createdAt: string; documentType?: string; transcription?: string; transcriptionReviewedAt?: string };
type Workspace = { version: 1; profile: { userType: string }; matters: Matter[]; entries: Entry[]; evidence: Evidence[] };
type Choice = { value: string; other: string };
type ModalName = "welcome" | "matter" | "entry" | "evidence" | "scan" | "upgrade" | "account" | null;
type Plan = "free" | "plus";

const blank: Workspace = { version: 1, profile: { userType: "" }, matters: [], entries: [], evidence: [] };
const matterTypes = ["Family & parenting", "Housing & property", "Freelance work", "Automotive repair", "Contractor project", "Shipping or delivery", "Legal or administrative"];
const eventTypes: Record<string, string[]> = {
  "Family & parenting": ["Exchange", "Schedule change", "Communication", "Child-related expense", "School", "Medical", "Missed parenting time", "Incident"],
  "Housing & property": ["Condition", "Maintenance request", "Notice", "Repair", "Expense", "Communication", "Inspection"],
  "Freelance work": ["Scope or requirement", "Approval", "Delivery", "Invoice", "Payment", "Expense", "Feedback", "Communication"],
  "Automotive repair": ["Intake condition", "Authorization", "Diagnostic", "Existing damage", "Repair progress", "Parts", "Road test", "Pickup or sign-off"],
  "Contractor project": ["Site condition", "Scope", "Change order", "Approval", "Progress", "Concealed work", "Completion", "Payment"],
};

const id = () => crypto.randomUUID();
const valueOf = (choice: Choice) => choice.value === "Other" ? choice.other.trim() : choice.value;
const when = (iso: string) => new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(iso));
const bytes = (size: number) => size < 1024 * 1024 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1024 / 1024).toFixed(1)} MB`;

export default function AppPage() {
  const [workspace, setWorkspace] = useState<Workspace>(blank);
  const [activeMatterId, setActiveMatterId] = useState("");
  const [modal, setModal] = useState<ModalName>(null);
  const [view, setView] = useState<"overview" | "timeline" | "evidence" | "export">("overview");
  const [status, setStatus] = useState("Loading your workspace…");
  const [loaded, setLoaded] = useState(false);
  const [plan, setPlan] = useState<Plan>("free");
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => { (async () => {
    try {
      const response = await fetch("/api/workspace", { cache: "no-store" });
      if (!response.ok) throw new Error();
      const data = await response.json() as { workspace: Workspace | null; plan?: Plan };
      const next = data.workspace || blank;
      setPlan(data.plan === "plus" ? "plus" : "free");
      setWorkspace(next); setActiveMatterId(next.matters[0]?.id || "");
      if (!next.profile.userType || !next.matters.length) setModal("welcome");
      setStatus(data.workspace ? "Saved securely" : "New workspace");
    } catch { setStatus("Unable to load workspace"); }
    setLoaded(true);
  })(); }, []);

  useEffect(() => { if (!loaded) return; const sessionId = new URLSearchParams(location.search).get("checkout"); if (!sessionId) return; (async()=>{ try { const response=await fetch(`/api/billing/confirm?session_id=${encodeURIComponent(sessionId)}`); if(!response.ok)throw new Error(); setPlan("plus"); setStatus("PROVya Plus unlocked"); history.replaceState({},"","/demo"); } catch { setStatus("Purchase verification failed"); } })(); }, [loaded]);

  useEffect(() => {
    if (!loaded) return;
    if (saveTimer.current) clearTimeout(saveTimer.current);
    setStatus("Saving…");
    saveTimer.current = setTimeout(async () => {
      try {
        const response = await fetch("/api/workspace", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(workspace) });
        setStatus(response.ok ? "Saved securely" : "Save failed");
      } catch { setStatus("Save failed"); }
    }, 450);
    return () => { if (saveTimer.current) clearTimeout(saveTimer.current); };
  }, [workspace, loaded]);

  const active = workspace.matters.find((matter) => matter.id === activeMatterId) || workspace.matters[0];
  const entries = useMemo(() => workspace.entries.filter((entry) => entry.matterId === active?.id).sort((a,b) => +new Date(b.happenedAt) - +new Date(a.happenedAt)), [workspace.entries, active]);
  const evidence = useMemo(() => workspace.evidence.filter((item) => item.matterId === active?.id), [workspace.evidence, active]);
  const update = (patch: Partial<Workspace>) => setWorkspace((current) => ({ ...current, ...patch }));
  const usage = { matters: workspace.matters.length, entries: workspace.entries.length, evidence: workspace.evidence.length, scans: workspace.evidence.filter(item=>item.transcription).length, storage: workspace.evidence.reduce((sum,item)=>sum+item.size,0) };
  const gated = (kind: keyof typeof usage) => plan === "free" && usage[kind] >= ({ matters:1, entries:25, evidence:10, scans:3, storage:100*1024*1024 })[kind];
  const openOrUpgrade = (target: ModalName, kind: keyof typeof usage) => gated(kind) ? setModal("upgrade") : setModal(target);

  function exportRecord() {
    if (!active) return;
    const record = { product: "PROVya", generatedAt: new Date().toISOString(), disclaimer: "Organization record only; not legal advice, forensic certification, or a guarantee of admissibility.", matter: active, timeline: entries, evidence };
    const url = URL.createObjectURL(new Blob([JSON.stringify(record, null, 2)], { type: "application/json" }));
    const a = document.createElement("a"); a.href = url; a.download = `${active.title.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-provya-record.json`; a.click(); URL.revokeObjectURL(url);
  }

  if (!loaded) return <main className="mvp-loading"><b>PROVya</b><span>{status}</span></main>;

  return <main className="mvp-app">
    <header className="mvp-top"><a href="/" className="mvp-wordmark">PROV<span>ya</span></a><button className={`plan-badge ${plan}`} onClick={()=>setModal("upgrade")}>{plan === "plus" ? "PLUS · LIFETIME" : "FREE PLAN"}</button><div className={`save-state ${status.includes("failed") || status.includes("Unable") ? "bad" : ""}`}><i />{status}</div><div className="mvp-actions"><button onClick={() => setModal("account")}>Account</button><button onClick={() => openOrUpgrade("matter","matters")}>New matter</button><button className="primary" disabled={!active} onClick={() => openOrUpgrade("entry","entries")}>+ Add entry</button></div></header>
    <aside className="mvp-side"><p>YOUR MATTERS</p><div className="matter-list">{workspace.matters.map((matter) => <button key={matter.id} className={matter.id === active?.id ? "active" : ""} onClick={() => { setActiveMatterId(matter.id); setView("overview"); }}><b>{matter.title}</b><span>{matter.type}</span></button>)}</div>{active && <nav>{([['overview','Overview'],['timeline','Timeline'],['evidence','Evidence'],['export','Export']] as const).map(([key,label]) => <button className={view === key ? "active" : ""} key={key} onClick={() => setView(key)}>{label}<em>{key === "timeline" ? entries.length : key === "evidence" ? evidence.length : ""}</em></button>)}</nav>}<div className="mvp-trust"><b>Private workspace</b><span>Your records are saved to your signed-in workspace.</span></div></aside>
    <section className="mvp-content">{!active ? <Empty onStart={() => setModal("welcome")} /> : <>
      <div className="mvp-heading"><div><span>{active.type}</span><h1>{active.title}</h1><p>{active.role} · {active.status}</p></div><div className="heading-actions"><button onClick={() => openOrUpgrade("scan","scans")}>Scan handwriting</button><button onClick={() => openOrUpgrade("evidence",gated("storage")?"storage":"evidence")}>Import evidence</button></div></div>
      {view === "overview" && <Overview entries={entries} evidence={evidence} onEntry={() => setModal("entry")} onEvidence={() => setModal("evidence")} />}
      {view === "timeline" && <Timeline entries={entries} onAdd={() => setModal("entry")} onDelete={(entryId) => update({ entries: workspace.entries.filter((entry) => entry.id !== entryId) })} />}
      {view === "evidence" && <EvidenceList items={evidence} onAdd={() => setModal("evidence")} onDelete={async (itemId) => { await fetch(`/api/evidence?id=${encodeURIComponent(itemId)}`, { method: "DELETE" }); update({ evidence: workspace.evidence.filter((item) => item.id !== itemId) }); }} />}
      {view === "export" && <ExportPanel active={active} entries={entries} evidence={evidence} onExport={exportRecord} />}
    </>}</section>
    {modal === "welcome" && <Welcome onSave={(profile, matter) => { update({ profile, matters: [matter] }); setActiveMatterId(matter.id); setModal(null); }} />}
    {modal === "matter" && <MatterModal onClose={() => setModal(null)} onSave={(matter) => { update({ matters: [...workspace.matters, matter] }); setActiveMatterId(matter.id); setModal(null); }} />}
    {modal === "entry" && active && <EntryModal matter={active} onClose={() => setModal(null)} onSave={(entry) => { update({ entries: [...workspace.entries, entry] }); setModal(null); setView("timeline"); }} />}
    {modal === "evidence" && active && <EvidenceModal matter={active} onClose={() => setModal(null)} onSave={(item) => { update({ evidence: [...workspace.evidence, item] }); setModal(null); setView("evidence"); }} />}
    {modal === "scan" && active && <ScanModal matter={active} onClose={() => setModal(null)} onSave={(item) => { update({ evidence: [...workspace.evidence, item] }); setModal(null); setView("evidence"); }} />}
    {modal === "upgrade" && <Upgrade plan={plan} usage={usage} onClose={()=>setModal(null)} />}
    {modal === "account" && <Account plan={plan} usage={usage} onClose={()=>setModal(null)} />}
  </main>;
}

function Account({plan,usage,onClose}:{plan:Plan;usage:{matters:number;entries:number;evidence:number;scans:number;storage:number};onClose:()=>void}) {
  const [confirmation,setConfirmation]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function downloadAccount(){setBusy(true);setError("");try{const response=await fetch("/api/account",{cache:"no-store"});if(!response.ok)throw new Error("Your account export could not be prepared.");const data=await response.json();const url=URL.createObjectURL(new Blob([JSON.stringify(data.export,null,2)],{type:"application/json"}));const anchor=document.createElement("a");anchor.href=url;anchor.download=`provya-account-export-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Export failed.");}finally{setBusy(false);}}
  async function deleteAccount(){if(confirmation!=="DELETE")return;setBusy(true);setError("");try{const response=await fetch("/api/account",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({confirmation})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error||"Account deletion failed.");location.href="/signout-with-chatgpt?return_to=/";}catch(e){setError(e instanceof Error?e.message:"Account deletion failed.");setBusy(false);}}
  return <Dialog title="Account and data" copy="Export what you control, get help, or permanently remove this PROVya workspace." onClose={onClose}><div className="account-summary"><div><span>PLAN</span><b>{plan==="plus"?"Plus · Lifetime":"Free"}</b></div><div><span>STORAGE</span><b>{bytes(usage.storage)} / {plan==="plus"?"2 GB":"100 MB"}</b></div><div><span>RECORDS</span><b>{usage.matters} matters · {usage.evidence} files</b></div></div><div className="account-actions"><button onClick={downloadAccount} disabled={busy}>Download account manifest</button><a href="/signout-with-chatgpt?return_to=/">Sign out</a><a href="mailto:support@tekpakinc.net?subject=PROVya%20support">Contact support</a></div><p className="account-explain">The account manifest includes workspace data and a list of stored files. Download each original from Evidence when you need a complete offline copy.</p><div className="danger-zone"><b>Delete this account permanently</b><p>This immediately deletes workspace records, stored originals, transcriptions, and the PROVya plan record. This cannot be undone. Payment-provider records may remain for required financial recordkeeping.</p><label className="mvp-field"><span>Type DELETE to confirm</span><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoComplete="off" /></label><button onClick={deleteAccount} disabled={busy||confirmation!=="DELETE"}>Permanently delete account</button></div>{error&&<p className="mvp-error">{error}</p>}<div className="account-legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/refunds">Refunds</a></div></Dialog>;
}

function Upgrade({plan,usage,onClose}:{plan:Plan;usage:{matters:number;entries:number;evidence:number;scans:number;storage:number};onClose:()=>void}) {
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function checkout(){setBusy(true);setError("");try{const response=await fetch("/api/billing/checkout",{method:"POST"});const data=await response.json() as {url?:string;error?:string};if(!response.ok||!data.url)throw new Error(data.error||"Checkout could not be started.");location.href=data.url;}catch(e){setError(e instanceof Error?e.message:"Checkout could not be started.");setBusy(false);}}
  return <Dialog title={plan==="plus"?"You have PROVya Plus":"Unlock the complete record"} copy={plan==="plus"?"Your lifetime license is active. There are no recurring software charges.":"One purchase unlocks every personal-use feature. No subscription."} onClose={onClose}>{plan==="free"&&<><div className="upgrade-price"><b>$39</b><span>one time</span></div><div className="upgrade-grid"><section><small>FREE</small><b>Good for trying PROVya</b><ul><li>1 active matter</li><li>25 timeline entries</li><li>10 evidence files</li><li>3 handwriting scans</li><li>100 MB secure storage</li></ul></section><section className="featured"><small>PLUS · LIFETIME</small><b>Complete personal use</b><ul><li>Unlimited matters and entries</li><li>Unlimited handwriting transcription</li><li>Reviewed transcription PDFs</li><li>Complete record exports</li><li>2 GB secure storage</li></ul></section></div><div className="usage-line">Free usage: {usage.matters}/1 matter · {usage.entries}/25 entries · {usage.evidence}/10 files · {usage.scans}/3 scans</div>{error&&<p className="mvp-error">{error}</p>}<button className="mvp-submit plus-submit" onClick={checkout} disabled={busy}>{busy?"Opening secure checkout…":"Get PROVya Plus — $39 once →"}</button><p className="upgrade-fine">Personal-use lifetime software license. Includes up to 2 GB hosted storage. No subscription.</p></>}{plan==="plus"&&<div className="plus-confirm"><b>✓ Lifetime access active</b><p>Unlimited matters, entries, handwriting transcription, PDFs, and up to 2 GB secure storage.</p></div>}</Dialog>;
}

function ChoiceField({ label, options, choice, setChoice }: { label: string; options: string[]; choice: Choice; setChoice: (choice: Choice) => void }) {
  return <label className="mvp-field"><span>{label}</span><select value={choice.value} onChange={(event) => setChoice({ value: event.target.value, other: "" })}><option value="">Select one</option>{options.map((option) => <option key={option}>{option}</option>)}<option>Other</option></select>{choice.value === "Other" && <input autoFocus value={choice.other} onChange={(event) => setChoice({ ...choice, other: event.target.value })} placeholder="Type your own" />}</label>;
}

function Dialog({ title, copy, onClose, children }: { title: string; copy: string; onClose?: () => void; children: React.ReactNode }) { return <div className="mvp-backdrop"><section className="mvp-dialog" role="dialog" aria-modal="true">{onClose && <button className="mvp-close" onClick={onClose}>×</button>}<small>PROVYA</small><h2>{title}</h2><p>{copy}</p>{children}</section></div>; }

function Welcome({ onSave }: { onSave: (profile: Workspace['profile'], matter: Matter) => void }) {
  const [user, setUser] = useState<Choice>({ value: "", other: "" }); const [type, setType] = useState<Choice>({ value: "", other: "" }); const [title, setTitle] = useState(""); const [accepted,setAccepted]=useState(false);
  const okay = valueOf(user) && valueOf(type) && title.trim() && accepted;
  return <Dialog title="Start your first record" copy="Tell PROVya what you are documenting. You can create unrelated matters later."><div className="mvp-grid"><ChoiceField label="I am a" options={["Parent or caregiver","Self-represented person","Freelancer or contractor","Business or service provider","Attorney or legal professional","Attorney's client"]} choice={user} setChoice={setUser}/><ChoiceField label="This matter is about" options={matterTypes} choice={type} setChoice={setType}/><label className="mvp-field full"><span>Matter name</span><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="e.g. Parenting record — 2026" /></label></div><label className="terms-check"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>I agree to the <a href="/terms" target="_blank">Terms</a> and <a href="/privacy" target="_blank">Privacy Policy</a>, and understand that PROVya does not provide legal advice or guarantee admissibility.</span></label><button className="mvp-submit" disabled={!okay} onClick={() => onSave({ userType: valueOf(user) }, { id: id(), title: title.trim(), type: valueOf(type), role: valueOf(user), status: "Active", createdAt: new Date().toISOString() })}>Create private workspace →</button></Dialog>;
}

function MatterModal({ onClose, onSave }: { onClose: () => void; onSave: (matter: Matter) => void }) {
  const [title,setTitle]=useState(""); const [type,setType]=useState<Choice>({value:"",other:""}); const [role,setRole]=useState<Choice>({value:"",other:""}); const [status,setStatus]=useState<Choice>({value:"Active",other:""});
  return <Dialog title="Create a matter" copy="Keep each situation separate so its timeline and evidence remain easy to follow." onClose={onClose}><div className="mvp-grid"><label className="mvp-field full"><span>Matter name</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="A short, recognizable name"/></label><ChoiceField label="Matter type" options={matterTypes} choice={type} setChoice={setType}/><ChoiceField label="Your role" options={["Parent","Tenant","Property owner","Client","Service provider","Vehicle owner","Attorney","Self-represented person"]} choice={role} setChoice={setRole}/><ChoiceField label="Status" options={["Active","Ongoing","Waiting","Resolved","Archived"]} choice={status} setChoice={setStatus}/></div><button className="mvp-submit" disabled={!title.trim() || !valueOf(type)} onClick={()=>onSave({id:id(),title:title.trim(),type:valueOf(type),role:valueOf(role)||"Not specified",status:valueOf(status),createdAt:new Date().toISOString()})}>Create matter →</button></Dialog>;
}

function EntryModal({ matter, onClose, onSave }: { matter: Matter; onClose: () => void; onSave: (entry: Entry) => void }) {
  const [type,setType]=useState<Choice>({value:"",other:""}); const [party,setParty]=useState<Choice>({value:"",other:""}); const [outcome,setOutcome]=useState<Choice>({value:"",other:""}); const [source,setSource]=useState<Choice>({value:"In-app note",other:""}); const [notes,setNotes]=useState(""); const [happenedAt,setHappenedAt]=useState(new Date().toISOString().slice(0,16));
  return <Dialog title="Document an entry" copy="Record facts while they are fresh. Avoid conclusions you cannot support." onClose={onClose}><div className="mvp-grid"><ChoiceField label="Entry type" options={eventTypes[matter.type] || ["Communication","Agreement","Incident","Expense","Document","Milestone"]} choice={type} setChoice={setType}/><ChoiceField label="Person or party" options={["Me","Co-parent","Client","Customer","Attorney","Contractor","Property manager","Repair shop"]} choice={party} setChoice={setParty}/><ChoiceField label="Outcome or status" options={["Completed","Acknowledged","Agreed","Declined","No response","Pending","Disputed"]} choice={outcome} setChoice={setOutcome}/><ChoiceField label="Source" options={["In-app note","Text message","Email","Photo or video","Receipt or invoice","PDF or document","Phone call summary"]} choice={source} setChoice={setSource}/><label className="mvp-field"><span>Date and time</span><input type="datetime-local" value={happenedAt} onChange={e=>setHappenedAt(e.target.value)}/></label><label className="mvp-field full"><span>What happened?</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write a factual summary. Names, actions, dates, and outcomes are most useful."/></label></div><button className="mvp-submit" disabled={!valueOf(type) || !notes.trim()} onClick={()=>onSave({id:id(),matterId:matter.id,type:valueOf(type),party:valueOf(party),outcome:valueOf(outcome),source:valueOf(source),happenedAt:new Date(happenedAt).toISOString(),notes:notes.trim(),createdAt:new Date().toISOString()})}>Save entry →</button></Dialog>;
}

function EvidenceModal({ matter, onClose, onSave }: { matter: Matter; onClose: () => void; onSave: (item: Evidence) => void }) {
  const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function upload(){ if(!file)return; setBusy(true); setError(""); try { const evidenceId=id(); const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,"0")).join(""); const form=new FormData(); form.set("file",file); form.set("evidenceId",evidenceId); form.set("hash",hash); const response=await fetch("/api/evidence",{method:"POST",body:form}); if(!response.ok) throw new Error((await response.json()).error); onSave({id:evidenceId,matterId:matter.id,name:file.name,mime:file.type||"application/octet-stream",size:file.size,hash,createdAt:new Date().toISOString()}); } catch(e){setError(e instanceof Error?e.message:"Upload failed.");setBusy(false);} }
  return <Dialog title="Import original evidence" copy="PROVya stores the file and records a SHA-256 fingerprint. This detects later file changes; it does not prove the content is true." onClose={onClose}><label className="mvp-drop"><input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/><b>{file?file.name:"Choose a photo, message export, document, or receipt"}</b><span>{file?bytes(file.size):"Maximum file size: 50 MB"}</span></label>{error&&<p className="mvp-error">{error}</p>}<button className="mvp-submit" disabled={!file||busy} onClick={upload}>{busy?"Hashing and uploading…":"Preserve file →"}</button></Dialog>;
}

function ScanModal({ matter, onClose, onSave }: { matter: Matter; onClose: () => void; onSave: (item: Evidence) => void }) {
  const [file,setFile]=useState<File|null>(null); const [preview,setPreview]=useState(""); const [text,setText]=useState(""); const [progress,setProgress]=useState(0); const [busy,setBusy]=useState(false); const [stage,setStage]=useState<"capture"|"review">("capture"); const [error,setError]=useState(""); const [documentType,setDocumentType]=useState<Choice>({value:"Journal entry",other:""});
  useEffect(()=>{ if(!file){setPreview("");return;} const url=URL.createObjectURL(file); setPreview(url); return()=>URL.revokeObjectURL(url); },[file]);
  async function transcribe(){ if(!file)return; setBusy(true); setError(""); try { const { createWorker }=await import("tesseract.js"); const worker=await createWorker("eng",1,{logger:(message)=>{if(message.status==="recognizing text")setProgress(Math.round((message.progress||0)*100));}}); const result=await worker.recognize(file); await worker.terminate(); setText(result.data.text.trim()); setStage("review"); } catch { setError("The handwriting could not be read. You can try a brighter, straighter photo."); } finally { setBusy(false); } }
  async function preserve(){ if(!file||!text.trim())return; setBusy(true); setError(""); try { const evidenceId=id(); const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(b=>b.toString(16).padStart(2,"0")).join(""); const form=new FormData(); form.set("file",file); form.set("evidenceId",evidenceId); form.set("hash",hash); const response=await fetch("/api/evidence",{method:"POST",body:form}); if(!response.ok)throw new Error(); onSave({id:evidenceId,matterId:matter.id,name:file.name,mime:file.type||"image/jpeg",size:file.size,hash,createdAt:new Date().toISOString(),documentType:valueOf(documentType)||"Handwritten document",transcription:text.trim(),transcriptionReviewedAt:new Date().toISOString()}); } catch { setError("The original image could not be stored. Please try again."); setBusy(false); } }
  return <Dialog title={stage==="capture"?"Scan handwritten notes":"Review the transcription"} copy={stage==="capture"?"Take a clear, straight photo in good light. Recognition happens in your browser; always compare the result with the original.":"Correct every uncertain word before saving. The original image remains unchanged and linked to this text."} onClose={onClose}>{stage==="capture"?<><ChoiceField label="Document type" options={["Journal entry","Parenting log","Handwritten agreement","Work notes","Inspection notes","Vehicle repair notes","Letter"]} choice={documentType} setChoice={setDocumentType}/><label className="mvp-drop scan-drop"><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/>{preview&&<img src={preview} alt="Selected handwritten page"/>}<b>{file?file.name:"Take a photo or choose an image"}</b><span>Use one page per scan for the best result.</span></label>{error&&<p className="mvp-error">{error}</p>}<button className="mvp-submit" disabled={!file||busy} onClick={transcribe}>{busy?`Reading handwriting… ${progress}%`:"Convert to text →"}</button></>:<><div className="scan-review"><img src={preview} alt="Original handwritten page"/><label className="mvp-field"><span>EDITABLE TRANSCRIPTION</span><textarea value={text} onChange={e=>setText(e.target.value)} /></label></div><div className="review-warning"><b>Compare line by line</b><span>Names, dates, dollar amounts, and uncommon words need special attention.</span></div>{error&&<p className="mvp-error">{error}</p>}<button className="mvp-submit" disabled={!text.trim()||busy} onClick={preserve}>{busy?"Preserving original and text…":"I reviewed this transcription — save both →"}</button></>}</Dialog>;
}

function Empty({ onStart }: { onStart: () => void }) { return <div className="mvp-empty"><span>01</span><h1>Build the record,<br/>not the argument.</h1><p>Create a matter, add factual entries, and preserve the files that support them.</p><button onClick={onStart}>Start your first record →</button></div>; }
function Overview({ entries,evidence,onEntry,onEvidence }: { entries:Entry[]; evidence:Evidence[]; onEntry:()=>void; onEvidence:()=>void }) { const last=entries[0]; return <><div className="mvp-metrics"><article><span>Timeline entries</span><b>{entries.length}</b></article><article><span>Evidence files</span><b>{evidence.length}</b></article><article><span>Files fingerprinted</span><b>{evidence.length ? "100%" : "—"}</b></article></div><div className="mvp-columns"><section className="mvp-panel"><small>NEXT BEST STEP</small><h2>{!entries.length?"Document what happened":!evidence.length?"Add supporting evidence":"Keep the timeline current"}</h2><p>{!entries.length?"Start with a factual event, communication, expense, or agreement.":!evidence.length?"Import the original photo, message export, receipt, or document.":"Add new developments as they occur; PROVya keeps them in event order."}</p><button onClick={!entries.length?onEntry:onEvidence}>{!entries.length?"Add first entry":"Import evidence"} →</button></section><section className="mvp-panel"><small>LATEST ACTIVITY</small>{last?<><h2>{last.type}</h2><p>{last.notes}</p><span>{when(last.happenedAt)}</span></>:<p>No activity yet.</p>}</section></div><Safety/></>; }
function Timeline({ entries,onAdd,onDelete }: { entries:Entry[]; onAdd:()=>void; onDelete:(id:string)=>void }) { return <section className="mvp-list"><div className="mvp-section-head"><div><small>CHRONOLOGY</small><h2>What happened, in order</h2></div><button onClick={onAdd}>+ Add entry</button></div>{!entries.length&&<p className="mvp-zero">No entries yet.</p>}{entries.map(entry=><article key={entry.id}><time>{when(entry.happenedAt)}</time><div><span>{entry.type}</span><h3>{entry.notes}</h3><p>{[entry.party,entry.outcome,entry.source].filter(Boolean).join(" · ")}</p></div><button className="danger" onClick={()=>confirm("Delete this entry?")&&onDelete(entry.id)}>Delete</button></article>)}</section>; }
async function downloadTranscriptionPdf(item: Evidence) {
  if(!item.transcription)return; const { jsPDF }=await import("jspdf"); const pdf=new jsPDF({unit:"pt",format:"letter"});
  pdf.setFont("helvetica","bold"); pdf.setFontSize(20); pdf.text("PROVya Transcription",54,60); pdf.setFontSize(11); pdf.setFont("helvetica","normal"); pdf.text(`${item.documentType || "Handwritten document"} · User reviewed`,54,82); pdf.setTextColor(90); pdf.text(`Original: ${item.name}`,54,104); pdf.text(`SHA-256: ${item.hash}`,54,120,{maxWidth:500}); pdf.setTextColor(0); pdf.setFontSize(12); const lines=pdf.splitTextToSize(item.transcription,504); let y=160; for(const line of lines){if(y>720){pdf.addPage();y=60;}pdf.text(line,54,y);y+=17;} pdf.setFontSize(8); pdf.setTextColor(100); const note="This is a user-reviewed transcription linked to a preserved original. PROVya does not certify authorship, truth, or admissibility."; pdf.text(pdf.splitTextToSize(note,504),54,760); pdf.save(`${item.name.replace(/\.[^.]+$/,"")}-transcription.pdf`);
}
function EvidenceList({items,onAdd,onDelete}:{items:Evidence[];onAdd:()=>void;onDelete:(id:string)=>void}) { return <section className="mvp-list"><div className="mvp-section-head"><div><small>SOURCE LIBRARY</small><h2>Original files and fingerprints</h2></div><button onClick={onAdd}>Import file</button></div>{!items.length&&<p className="mvp-zero">No evidence files yet.</p>}{items.map(item=><article key={item.id}><div className="file-icon">{item.transcription?"TXT":item.name.split('.').pop()?.slice(0,4).toUpperCase()}</div><div><span>{item.documentType || when(item.createdAt)}{item.transcription&&" · User-reviewed transcription"}</span><h3>{item.name}</h3><p>{bytes(item.size)} · SHA-256 {item.hash.slice(0,12)}…{item.hash.slice(-8)}</p></div>{item.transcription&&<button className="text-action" onClick={()=>downloadTranscriptionPdf(item)}>Text PDF</button>}<a href={`/api/evidence?id=${encodeURIComponent(item.id)}`}>Original</a><button className="danger" onClick={()=>confirm("Delete this stored file and its transcription?")&&onDelete(item.id)}>Delete</button></article>)}</section>; }
function ExportPanel({active,entries,evidence,onExport}:{active:Matter;entries:Entry[];evidence:Evidence[];onExport:()=>void}) { return <div className="mvp-export"><small>PORTABLE RECORD</small><h2>Take a copy you control.</h2><p>Download a structured JSON record containing this matter, its timeline, and the integrity fingerprints for its evidence files.</p><dl><div><dt>Matter</dt><dd>{active.title}</dd></div><div><dt>Timeline</dt><dd>{entries.length} entries</dd></div><div><dt>Evidence</dt><dd>{evidence.length} files</dd></div></dl><button onClick={onExport}>Download matter record ↓</button><Safety/></div>; }
function Safety(){return <div className="mvp-safety"><b>Important limitation</b><p>PROVya organizes and preserves what you provide. It does not verify truth, give legal advice, certify forensic authenticity, or guarantee that material will be accepted by a court or other decision-maker.</p></div>;}
