const features = [
  { n: "01", title: "Preserve the source", copy: "Import messages, photos, receipts, and files while keeping every original untouched and traceable." },
  { n: "02", title: "Build the record", copy: "Guided protocols show what to collect, then connect each item to a clear event chronology." },
  { n: "03", title: "Prepare the packet", copy: "Create a readable evidence packet, numbered exhibits, and an integrity manifest for review." },
];
const uses = ["Message transcripts", "Housing conditions", "Property damage", "Shipping disputes", "Service records", "Attorney handoff"];

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Primary navigation"><a className="brand" href="#top"><span>PROV</span><i>ya</i></a><div className="navlinks"><a href="#how">How it works</a><a href="#uses">Use cases</a><a href="#pricing">Pricing</a></div><a className="nav-cta" href="/signin-with-chatgpt?return_to=%2Fdemo">Sign in <span>↗</span></a></nav>
    <section className="hero shell" id="top">
      <div className="hero-copy"><div className="eyebrow"><span className="pulse" /> Evidence, organized</div><h1>When it matters,<br /><em>PROV</em> the record.</h1><p className="lede">Turn scattered messages, photos, documents, and dates into one source-preserving evidence packet someone else can actually follow.</p><div className="hero-actions"><a className="button primary" href="/demo">Open interactive demo <span>→</span></a><a className="text-link" href="#how">See how it works <span>↓</span></a></div><div className="trust-row"><div><b>Local-first</b><span>Your record stays yours.</span></div><div><b>Traceable</b><span>Originals remain linked.</span></div><div><b>Guided</b><span>Know what to collect.</span></div></div></div>
      <div className="hero-visual" aria-label="PROVya evidence packet preview"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="float-card card-top"><span className="check">✓</span><div><b>Sources preserved</b><small>Messages · photos · receipts</small></div></div><div className="phone"><div className="phone-top"><span>9:41</span><i/></div><div className="app-head"><div className="mini-brand">PROV<i>ya</i></div><span className="avatar">ML</span></div><p className="screen-label">ACTIVE MATTER</p><h3>Morgan v. Crestview</h3><div className="meta"><span>● Building record</span><span>Housing</span></div><div className="photo-grid"><div className="photo p1"><span>EX-01</span></div><div className="photo p2"><span>EX-02</span></div><div className="photo p3"><span>EX-03</span></div></div><div className="timeline"><div><i className="done">✓</i><p><b>Starting condition</b><span>Original video preserved</span></p></div><div><i className="done">✓</i><p><b>Written notice</b><span>24-message transcript</span></p></div><div><i>3</i><p><b>Final outcome</b><span>Recommended</span></p></div></div><a className="report-button" href="/demo">Preview evidence packet <span>↗</span></a></div><div className="float-card card-bottom"><span className="pdf">JSON</span><div><b>Integrity manifest</b><small>Every source accounted for.</small></div></div></div>
    </section>
    <section className="ticker"><div>SOURCE PRESERVATION <span>✦</span> MESSAGE TRANSCRIPTS <span>✦</span> CLEAR TIMELINES <span>✦</span> EVIDENCE PACKETS <span>✦</span> SOURCE PRESERVATION</div></section>
    <section className="how shell" id="how"><div className="section-head"><span>HOW IT WORKS</span><h2>From scattered files<br/>to <em>one clear record.</em></h2></div><div className="feature-list">{features.map((feature)=><article key={feature.n}><span className="feature-num">{feature.n}</span><h3>{feature.title}</h3><p>{feature.copy}</p><span className="feature-arrow">↗</span></article>)}</div></section>
    <section className="use-section" id="uses"><div className="shell use-grid"><div className="use-copy"><span className="kicker">NOT A CASE-MANAGEMENT SYSTEM.</span><h2>The record before<br/><em>the argument.</em></h2><p>PROVya helps people preserve and organize what they already have. It does not provide legal advice, determine truth, or promise admissibility.</p><a className="button light" href="/demo">Experience the demo <span>→</span></a></div><div className="use-list">{uses.map((use,index)=><div key={use}><span>0{index+1}</span><b>{use}</b><i>↗</i></div>)}</div></div></section>
    <section className="quote shell"><p>“Don&apos;t just collect everything.<br/><em>Build a record they can follow.</em>”</p><span>PROVYA EVIDENCE PACK · BY TEK-PAK INC.</span></section>
    <section className="pricing-section shell" id="pricing"><div className="section-head"><span>SIMPLE PRICING</span><h2>Start free.<br/><em>Keep Plus forever.</em></h2></div><div className="pricing-grid"><article><span>PROVYA FREE</span><h3>$0</h3><p>Build your first organized record.</p><ul><li>1 active matter</li><li>25 timeline entries</li><li>10 evidence files</li><li>3 handwriting scans</li><li>100 MB secure storage</li></ul><a href="/demo">Start free →</a></article><article className="plus-card"><span>PROVYA PLUS · LIFETIME</span><h3>$39 <small>once</small></h3><p>The complete personal-use product. No subscription.</p><ul><li>Unlimited matters and entries</li><li>Unlimited handwriting transcription</li><li>User-reviewed transcription PDFs</li><li>Complete record exports</li><li>2 GB secure storage</li></ul><a href="/demo">Get Plus →</a></article></div><p className="pricing-note">Personal-use lifetime software license. Hosted storage is capped at the amount shown. Export your records anytime.</p></section>
    <section className="cta-wrap shell"><div className="cta-panel"><span className="cta-mark">P<span>✓</span></span><div><span className="kicker">START WITH ONE RECORD</span><h2>Evidence made<br/><em>easy.</em></h2></div><div className="signup"><p>Create a private matter, document the timeline, preserve original files, and scan handwritten notes into reviewed text.</p><a className="button primary" href="/demo">Start free <span>→</span></a></div></div></section>
    <footer className="shell footer"><div className="brand footer-brand"><span>PROV</span><i>ya</i></div><p>Evidence, organized.<br/>A Tek-Pak Inc. product.</p><div><a href="/signin-with-chatgpt?return_to=%2Fdemo">Sign in</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/refunds">Refunds</a><a href="/support">Support</a></div><span>© 2026 TEK-PAK INC.</span></footer>
  </main>;
}
